### ISSUE TITLE
Weird sorting in Centralinks

### ISSUE THREAD

**Issue by nymous** [korween/centralink#4]
I have a Centralink awaiting approval, planned for the 25/03/2016.
If I create a new Centralink, it is above the awaiting one if its send date is before the 20th of any month or year, and under if the send date is after the 21st of any month or year.

FF 46

**Comment by korween** [comment]
Sorting is messed up while creating a new message only on my side. Also, one month gets added to the chosen date.

**Comment by nymous** [comment]
You mean on the "front side"? And what about that month?
